import turtle
a=turtle.Turtle()
screen=turtle.Screen()
screen.setup(400,300)
screen.bgcolor("green")
a.pencolor("red")
a.pensize(5)
a.speed(1)
a.forward(100)
a.left(90)
a.penup()
a.forward(100)
a.pendown()
a.left(90)
a.forward(200)
a.left(120)
a.forward(200)
turtle.exitonclick()